apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
     name: server-pod
     labels:
      app: server
    spec:
      containers:
        - name: server
          image: pongphisut/testm

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30002